
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __NST_ENUM_TYPES_H__
#define __NST_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from "caja-sendto-plugin.h" */
GType nst_plugin_capabilities_get_type (void);
#define NST_TYPE_PLUGIN_CAPABILITIES (nst_plugin_capabilities_get_type())
G_END_DECLS

#endif /* __NST_ENUM_TYPES_H__ */

/* Generated data ends here */

