
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include <caja-sendto-plugin.h>
#include "nst-enum-types.h"
#include <glib-object.h>

/* enumerations from "caja-sendto-plugin.h" */
GType
nst_plugin_capabilities_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GFlagsValue values[] = {
      { CAJA_CAPS_NONE, "CAJA_CAPS_NONE", "none" },
      { CAJA_CAPS_SEND_DIRECTORIES, "CAJA_CAPS_SEND_DIRECTORIES", "send-directories" },
      { CAJA_CAPS_SEND_IMAGES, "CAJA_CAPS_SEND_IMAGES", "send-images" },
      { 0, NULL, NULL }
    };
    etype = g_flags_register_static ("NstPluginCapabilities", values);
  }
  return etype;
}

/* Generated data ends here */

